//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.EntityClient;

using RoRoWo.Blog.Domain.Entities;

namespace RoRoWo.Blog.Infrastructure
{
    public partial class RoRoWoDBEntities : ObjectContext
    {
       public const string ConnectionString = "name=RoRoWoDBEntities";
       public const string ContainerName = "RoRoWoDBEntities";
    
       #region Constructors
    
       public RoRoWoDBEntities()
           : base(ConnectionString, ContainerName)
       {
           
    	   //是否延迟加载
           this.ContextOptions.LazyLoadingEnabled = true;
    	   //是否创建代理
    	   this.ContextOptions.ProxyCreationEnabled = false;
       }
    
    /*
       public RoRoWoDBEntities(string connectionString)
           : base(connectionString, ContainerName)
       {
           this.ContextOptions.LazyLoadingEnabled = true;
    
    
       }
    
       public RoRoWoDBEntities(EntityConnection connection)
           : base(connection, ContainerName)
       {
           this.ContextOptions.LazyLoadingEnabled = true;
       }
    
       */
    
       #endregion
    
        #region ObjectSet Properties
    
       public ObjectSet<BlogArticle> BlogArticle
       {
           get { return _blogArticle  ?? (_blogArticle = CreateObjectSet<BlogArticle>("BlogArticle")); }
       }
       private ObjectSet<BlogArticle> _blogArticle;
    
       public ObjectSet<BlogCategory> BlogCategory
       {
           get { return _blogCategory  ?? (_blogCategory = CreateObjectSet<BlogCategory>("BlogCategory")); }
       }
       private ObjectSet<BlogCategory> _blogCategory;
    
       public ObjectSet<BlogComment> BlogComment
       {
           get { return _blogComment  ?? (_blogComment = CreateObjectSet<BlogComment>("BlogComment")); }
       }
       private ObjectSet<BlogComment> _blogComment;
    
       public ObjectSet<BlogDigg> BlogDigg
       {
           get { return _blogDigg  ?? (_blogDigg = CreateObjectSet<BlogDigg>("BlogDigg")); }
       }
       private ObjectSet<BlogDigg> _blogDigg;
    
       public ObjectSet<BlogMaster> BlogMaster
       {
           get { return _blogMaster  ?? (_blogMaster = CreateObjectSet<BlogMaster>("BlogMaster")); }
       }
       private ObjectSet<BlogMaster> _blogMaster;
    
       public ObjectSet<BlogTag> BlogTag
       {
           get { return _blogTag  ?? (_blogTag = CreateObjectSet<BlogTag>("BlogTag")); }
       }
       private ObjectSet<BlogTag> _blogTag;

        #endregion
    }
}
