//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace RoRoWo.Blog.Domain.Entities
{
    public partial class BlogTag
    {
        #region Primitive Properties
    
        public virtual int TagID
        {
            get;
            set;
        }
    
        public virtual string TagName
        {
            get;
            set;
        }
    
        public virtual int ParentID
        {
            get;
            set;
        }
    
        public virtual int State
        {
            get;
            set;
        }
    
        public virtual int SortID
        {
            get;
            set;
        }
    
        public virtual int ArticleCount
        {
            get;
            set;
        }
    
        public virtual System.DateTime CreateTime
        {
            get;
            set;
        }
    
        public virtual string Note
        {
            get;
            set;
        }

        #endregion
    }
}
