//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace RoRoWo.Blog.Domain.Entities
{
    public partial class BlogMaster
    {
        #region Primitive Properties
    
        public virtual int UserID
        {
            get;
            set;
        }
    
        public virtual string UserAccount
        {
            get;
            set;
        }
    
        public virtual string NickName
        {
            get;
            set;
        }
    
        public virtual string UserPassWord
        {
            get;
            set;
        }
    
        public virtual bool IsSystem
        {
            get;
            set;
        }
    
        public virtual Nullable<int> State
        {
            get;
            set;
        }
    
        public virtual System.DateTime CreateTime
        {
            get;
            set;
        }
    
        public virtual int LoginCount
        {
            get;
            set;
        }
    
        public virtual System.DateTime LastLogin
        {
            get;
            set;
        }
    
        public virtual string Note
        {
            get;
            set;
        }

        #endregion
    }
}
